site_name: Hexagons! Docs
site_dir: docs_build
pages:
    - Home: index.md
    - Creating levels: mapping.md
    - Scripting:
      - Callbacks: scripting/callbacks.md
      - Event system: scripting/events.md
      - Functions: scripting/functions.md
      - Properties: scripting/properties.md
      - Built-in patterns: scripting/standardPatterns.md
      - Pattern components: scripting/componentPatterns.md
theme: readthedocs